# ./docker-compose.yml

version: '3.1'

services:
  db:
    image: mariadb
    restart: always
    volumes:
      - ./db/:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  app:
    build:
      context: ./php
      dockerfile: ./Dockerfile
    container_name: php_app
    depends_on:
      - db
    volumes:
      - ./app/:/var/www/html/
    ports:
      - "80:80"
    stdin_open: true
    tty: true